### ISSUE TITLE
New Sen2Like version 4.4.0 version not fusing/harmonising L8 data

### ISSUE THREAD

**Issue by dalekmitzy** [senbox-org/sen2like#1]
The latest release of Sen2Like seems to not fuse/harmonise L8 data, just Sentinel? I tested and ran the previous version 3.3.0 using exact same inputs and didn't have this issue. 

Each time we try to run the latest version get the following error output:

"AttributeError: 'Landsat8Product' object has no attribute 'collection_number'"

**Comment by telespazio-tim** [comment]
Thank you for your issue.
It was due to metadata ingestion issue when reading Landsat 8 data. This issue has been resolved, and correction embedded in the Sen2Like 4.0.1 version.
